Дипломная работа
helensereda/AQATestRail pull request #6
Opened 2023-09-21 15:46 UTC by buykoam

2023-10-01 21:01 UTC, wildpioneer requested changes

2023-10-01 21:01 UTC, wildpioneer commented on src/test/java/baseEntities/BasePage.java
> +    protected abstract By getTitle1();
Не очень информативное название переменной

2023-10-01 21:01 UTC, wildpioneer commented on src/test/java/baseEntities/BasePage.java
> +    public boolean isPageOpened() {
Форматирование - пустые строки между методами

2023-10-01 21:01 UTC, wildpioneer commented on src/test/java/pages/AddProjectPage.java
> +    private final By nameLocator = By.xpath("//*[@id=\"name\"]");
???? Странный локатор

2023-10-01 21:01 UTC, wildpioneer commented on src/test/java/pages/DashboardPage.java
> +    private final By testLocator = By.xpath("//*[@id=\"project-10\"]/div[2]/div[2]/a[3]");
Это точно единственный вариант локатора?

2023-10-01 21:01 UTC, wildpioneer commented on src/test/java/pages/ProjectsPage.java
> +    private final By checkboxLocator = By.xpath("//*[@id=\"deleteDialog\"]/div[2]/div/div");
???

2023-10-01 21:01 UTC, wildpioneer commented on src/test/java/pages/ProjectsPage.java
> +    private final By deleteButtonLocator = By.xpath("//*[@id=\"deleteDialog\"]/div[3]/a[1]");
???

2023-10-03 17:26 UTC, helensereda commented on src/test/java/baseEntities/BasePage.java
> +    protected abstract By getTitle1();
Поправили

2023-10-03 17:26 UTC, helensereda commented on src/test/java/baseEntities/BasePage.java
> +    public boolean isPageOpened() {
Поправили

2023-10-03 17:26 UTC, helensereda commented on src/test/java/pages/AddProjectPage.java
> +    private final By nameLocator = By.xpath("//*[@id=\"name\"]");
Изменили локатор

2023-10-03 17:26 UTC, helensereda commented on src/test/java/pages/DashboardPage.java
> +    private final By testLocator = By.xpath("//*[@id=\"project-10\"]/div[2]/div[2]/a[3]");
Изменили локатор

2023-10-03 17:29 UTC, helensereda commented on src/test/java/pages/ProjectsPage.java
> +    private final By checkboxLocator = By.xpath("//*[@id=\"deleteDialog\"]/div[2]/div/div");
Изменили локаторы

2023-10-03 17:31 UTC, helensereda commented on src/test/java/pages/ProjectsPage.java
> +    private final By deleteButtonLocator = By.xpath("//*[@id=\"deleteDialog\"]/div[3]/a[1]");
![image](https://github.com/helensereda/AQATestRail/assets/131658858/7018fc45-54b6-43b0-bd45-d0ebfa7fade4)

2023-10-03 17:31 UTC, helensereda commented on src/test/java/pages/ProjectsPage.java
> +    private final By deleteButtonLocator = By.xpath("//*[@id=\"deleteDialog\"]/div[3]/a[1]");
Изменили локаторы

2023-10-04 09:16 UTC, wildpioneer commented on src/test/java/baseEntities/BasePage.java
> +    public boolean isPageOpened() {
Так надо наоборот - добавить пустые строки

2023-10-04 09:17 UTC, wildpioneer commented on src/test/java/pages/ProjectsPage.java
> +    private final By deleteButtonLocator = By.xpath("//*[@id=\"deleteDialog\"]/div[3]/a[1]");
Тут проблема с индексами - реально надо использовать индексы?

2023-10-04 09:18 UTC, merged